version: '3.8'
services:
  API:
    image: u-impact
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/uimpactdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres:13.3-alpine
    ports:
      - "5432:5432"

    environment:
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - POSTGRES_DB=uimpactdb
      - POSTGRES_HOST_AUTH_METHOD=trust
